### ISSUE TITLE
How do we intend to infer the `_field_name`?

### ISSUE THREAD

**Issue by jmmaljaars** [LEoPart-X/LEoPart#12]
See 

https://github.com/LEoPart-X/LEoPart/blob/0e5188805e6ecba9ce75ac8f2573859baba6db8f/src/particles.h#L47

I would suggest the field name is something that the user optionally _can_ specify, so no necessity?

**Comment by chrisrichardson** [comment]
Clearly this is not *necessary*, however it might be nice to have, especially for debugging.

**Comment by jmmaljaars** [comment]
Ok!
